# Generated by Django 3.1.7 on 2021-03-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='treasure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.treasure'),
        ),
    ]
