# Generated by Django 3.1.7 on 2021-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attempt_treasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
